# Generated by Django 2.2.3 on 2019-07-06 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('isbn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('issued', models.PositiveIntegerField(default=0)),
                ('deactive', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBasicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Custom', max_length=20)),
                ('maxBook', models.PositiveSmallIntegerField()),
                ('maxDay', models.IntegerField()),
                ('finePerDay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('count_books', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.CharField(max_length=20)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='LMS.UserBasicSetting')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.PositiveIntegerField()),
                ('issuefrom', models.CharField(max_length=20)),
                ('is_returned', models.BooleanField(default=False)),
                ('countrenewal', models.PositiveIntegerField(default=0)),
                ('issued_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(default=None, null=True)),
                ('duedate', models.DateTimeField()),
                ('mail_send', models.BooleanField(default=False)),
                ('autorenew', models.BooleanField(default=False)),
                ('forgetoverdue', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.ISBN')),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('isHOD', models.BooleanField(default=False)),
                ('branch', models.CharField(max_length=20)),
                ('count_books', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='LMS.UserBasicSetting')),
            ],
        ),
    ]
