# Generated by Django 2.2.1 on 2019-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasicsetting',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbasicsetting',
            name='type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
