# Generated by Django 2.2.1 on 2019-05-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20190522_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasicsetting',
            old_name='fineperDay',
            new_name='finePerDay',
        ),
    ]
