# Generated by Django 2.2.3 on 2019-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20190707_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='costPerDay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
