# Generated by Django 2.2.1 on 2019-05-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20190522_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.ISBN')),
            ],
        ),
    ]
