# Generated by Django 2.2.3 on 2019-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20190707_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='count_books',
            new_name='count_issues',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='count_books',
            new_name='count_issues',
        ),
        migrations.AddField(
            model_name='faculty',
            name='issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='isbn',
            name='count_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='issued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
