# Generated by Django 2.2.3 on 2019-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_auto_20190707_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='return_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
