# Generated by Django 2.2.3 on 2019-07-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20190707_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='forgetoverdue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='mail_send',
        ),
    ]
