# Generated by Django 2.2.1 on 2019-05-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_auto_20190528_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='member_id',
            field=models.PositiveIntegerField(),
        ),
    ]
