# Generated by Django 2.2.1 on 2019-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_auto_20190531_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='subject',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='unKonwn', max_length=20),
        ),
    ]
