# Generated by Django 2.2.3 on 2019-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_auto_20190707_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
