# Generated by Django 2.2.1 on 2019-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20190531_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=20),
        ),
    ]
