# Generated by Django 2.2.1 on 2019-05-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20190528_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_day',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='return_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
