# Generated by Django 2.2.3 on 2019-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_faculty_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
