# Generated by Django 2.2.1 on 2019-05-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_auto_20190528_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='issued',
            new_name='is_issued',
        ),
        migrations.AddField(
            model_name='issue',
            name='mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
