# Generated by Django 2.2.1 on 2019-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_auto_20190531_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='return_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
