# Generated by Django 2.2.1 on 2019-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_issue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='return_date',
            field=models.DateTimeField(default=None),
        ),
    ]
