# Generated by Django 2.2.1 on 2019-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_student_count_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='count_books',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
