# Generated by Django 2.2.3 on 2019-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_auto_20190719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attentionMessage',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
