# Generated by Django 2.2.1 on 2019-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_auto_20190603_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='duedate',
            field=models.DateTimeField(),
        ),
    ]
