# Generated by Django 2.2.1 on 2019-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_faculty_count_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
