# Generated by Django 2.2.1 on 2019-05-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_auto_20190528_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='account',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='account',
        ),
        migrations.RemoveField(
            model_name='student',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='ISBN',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='UserBasicSetting',
        ),
    ]
