# Generated by Django 2.2.3 on 2019-07-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_auto_20190719_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attentionMessage',
        ),
    ]
