# Generated by Django 2.2.1 on 2019-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_auto_20190528_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_day',
            new_name='checkedout',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='return_day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='issue',
            name='duedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
