# Generated by Django 2.2.1 on 2019-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_auto_20190529_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='countrenewal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
