# Generated by Django 2.2.1 on 2019-05-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_issue_countrenewal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
