# Generated by Django 2.2.1 on 2019-05-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
